# Generated by Django 4.0.6 on 2022-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(check=models.Q(('office_count__lte', 100)), name='office_count_lte_100'),
        ),
    ]
