# Generated by Django 4.0.6 on 2022-07-16 12:00

from django.db import migrations

def migrate_db(apps, schema_editor):
    Donate = apps.get_model('donation', 'Donate')
    for donate in Donate.objects.all():
        donate.name = donate.name
        donate.amount = donate.amount
        donate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_db)
    ]
