# Generated by Django 4.0.6 on 2022-08-04 10:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_office_office_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='office',
            name='office_count_lte_100',
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(check=models.Q(('office_count__lte', django.db.models.expressions.F('capacity'))), name='office_count_lte'),
        ),
    ]
