# Generated by Django 4.0.6 on 2022-07-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20220716_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='donate',
            name='state',
            field=models.CharField(choices=[('Available', 'Available'), ('Requested', 'Requested'), ('Booked', 'Booked'), ('Shipped', 'Shipped')], default='Available', max_length=100),
        ),
        migrations.AddField(
            model_name='donate',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.office'),
        ),
    ]
