# Generated by Django 4.0.6 on 2022-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_remove_office_office_count_lte_100_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_count',
            field=models.IntegerField(default=0),
        ),
    ]
