# Generated by Django 4.0.6 on 2022-08-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_alter_office_office_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(default=0)),
            ],
        ),
    ]
