# Generated by Django 4.0.6 on 2022-08-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.office'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_amount',
            field=models.IntegerField(default=0),
        ),
    ]
