# Generated by Django 4.0.6 on 2022-08-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_request_name_request_office_request_request_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='office',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
        migrations.CreateModel(
            name='Request_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.office')),
                ('request_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.request')),
            ],
        ),
    ]
