# Generated by Django 4.0.6 on 2022-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_rename_name_request_item_name_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
